project:
  type: website
  output-dir: docs

website:
  title: "ueuropeia_economics_tourism"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - material.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    from: markdown+emoji
    css: styles.css
    toc: true



